import networkx as nx
G = nx.Graph()
G.add_edge(1, 2)
G.add_edge(1, 4)
G.add_edge(2, 3)
G.add_edge(2, 5)
G.add_edge(4, 5)
G.add_edge(4, 7)
G.add_edge(8, 7)
G.add_edge(8, 9)
G.add_edge(6, 3)
G.add_edge(6, 9)
G.add_edge(6, 5)
